"""initial schema

Revision ID: a08ce48db4df
Revises: 
Create Date: 2026-09-04 23:07:21.241879+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a08ce48db4df'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('name_zh', sa.String(length=512), nullable=True),
    sa.Column('countries', sa.String(length=512), nullable=True),
    sa.Column('program', sa.String(length=512), nullable=True),
    sa.Column('listed_on', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_type', 'source', 'external_id')
    )
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_list_type'), ['list_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_source'), ['source'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('AGENT', 'SUPERVISOR', 'COMPLIANCE', 'AUDITOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('agent_license_no', sa.String(length=64), nullable=True),
    sa.Column('license_valid_until', sa.Date(), nullable=True),
    sa.Column('aml_training_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('watchlist_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('normalized', sa.String(length=512), nullable=False),
    sa.Column('sort_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['watchlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_names_entry_id'), ['entry_id'], unique=False)
        batch_op.create_index('ix_watchlist_names_lookup', ['normalized', 'sort_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_names_normalized'), ['normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_names_sort_key'), ['sort_key'], unique=False)

    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('org_unit_id', sa.Integer(), nullable=True),
    sa.Column('questionnaire_id', sa.String(length=32), nullable=False),
    sa.Column('questionnaire_version', sa.Integer(), nullable=False),
    sa.Column('holder_name_enc', sa.Text(), nullable=True),
    sa.Column('holder_id_enc', sa.Text(), nullable=True),
    sa.Column('holder_id_bidx', sa.String(length=64), nullable=True),
    sa.Column('insured_name_enc', sa.Text(), nullable=True),
    sa.Column('beneficiary_name_enc', sa.Text(), nullable=True),
    sa.Column('insurer_name', sa.String(length=128), nullable=True),
    sa.Column('policy_no', sa.String(length=64), nullable=True),
    sa.Column('annual_premium', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'BLOCKED', 'CLOSED', name='assessmentstatus'), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Enum('GENERAL', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('override_applied', sa.Boolean(), nullable=False),
    sa.Column('override_reasons', sa.Text(), nullable=True),
    sa.Column('blocked_reasons', sa.Text(), nullable=True),
    sa.Column('watchlist_hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('watchlist_hit_note', sa.Text(), nullable=True),
    sa.Column('consulted_supervisor', sa.Boolean(), nullable=False),
    sa.Column('consulted_name', sa.String(length=64), nullable=True),
    sa.Column('consulted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wealth_source', sa.Text(), nullable=True),
    sa.Column('fund_source_detail', sa.Text(), nullable=True),
    sa.Column('edd_note', sa.Text(), nullable=True),
    sa.Column('checks_json', sa.Text(), nullable=True),
    sa.Column('str_reported', sa.Boolean(), nullable=False),
    sa.Column('str_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('str_reference', sa.String(length=64), nullable=True),
    sa.Column('offshore_remittance', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retain_until', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessments_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_case_no'), ['case_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_assessments_holder_id_bidx'), ['holder_id_bidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_total_score'), ['total_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessments_watchlist_hit_at'), ['watchlist_hit_at'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)

    op.create_table('report_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('period_label', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('factor_code', sa.String(length=64), nullable=False),
    sa.Column('option_code', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'factor_code')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.Enum('AGENT', 'SUPERVISOR', 'COMPLIANCE', 'AUDITOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_assessment_id'), ['assessment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_assessment_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_assessment_id'))

    op.drop_table('answers')
    op.drop_table('report_exports')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_events')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_watchlist_hit_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_total_score'))
        batch_op.drop_index(batch_op.f('ix_assessments_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_assessments_risk_level'))
        batch_op.drop_index(batch_op.f('ix_assessments_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_assessments_holder_id_bidx'))
        batch_op.drop_index(batch_op.f('ix_assessments_case_no'))
        batch_op.drop_index(batch_op.f('ix_assessments_agent_id'))

    op.drop_table('assessments')
    with op.batch_alter_table('watchlist_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_names_sort_key'))
        batch_op.drop_index(batch_op.f('ix_watchlist_names_normalized'))
        batch_op.drop_index('ix_watchlist_names_lookup')
        batch_op.drop_index(batch_op.f('ix_watchlist_names_entry_id'))

    op.drop_table('watchlist_names')
    op.drop_table('users')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_source'))
        batch_op.drop_index(batch_op.f('ix_watchlist_list_type'))
        batch_op.drop_index(batch_op.f('ix_watchlist_batch'))
        batch_op.drop_index(batch_op.f('ix_watchlist_active'))

    op.drop_table('watchlist')
    op.drop_table('org_units')
    # ### end Alembic commands ###
