"""periodic review

Revision ID: 373902b9c6cc
Revises: a08ce48db4df
Create Date: 2026-09-04 23:47:50.419956+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '373902b9c6cc'
down_revision: str | None = 'a08ce48db4df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _risk_level_type(bind) -> sa.types.TypeEngine:
    """沿用既有的 risklevel 型別，不重新建立。

    PostgreSQL 的 Enum 是資料庫層級的具名型別，第一個遷移建立 assessments 時已建過。
    這裡若再 CREATE TYPE 會直接失敗——而 SQLite 把 Enum 存成 VARCHAR，沒有具名型別，
    因此這個錯誤在 SQLite 上完全測不出來，只會在正式環境套用遷移時才炸。
    """
    if bind.dialect.name == "postgresql":
        from sqlalchemy.dialects import postgresql

        return postgresql.ENUM("GENERAL", "HIGH", name="risklevel", create_type=False)
    return sa.Enum("GENERAL", "HIGH", name="risklevel")


def upgrade() -> None:
    bind = op.get_bind()
    risk_level = _risk_level_type(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Enum('UNCHANGED', 'ESCALATED', 'DEESCALATED', 'REASSESS', 'TERMINATED', name='reviewoutcome'), nullable=False),
    sa.Column('risk_level_before', risk_level, nullable=True),
    sa.Column('risk_level_after', risk_level, nullable=True),
    sa.Column('watchlist_hit', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('next_due_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('periodic_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodic_reviews_assessment_id'), ['assessment_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_due_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed_on', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rescreened_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_review_due_on'), ['review_due_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_review_due_on'))
        batch_op.drop_column('rescreened_at')
        batch_op.drop_column('last_reviewed_on')
        batch_op.drop_column('review_due_on')

    with op.batch_alter_table('periodic_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodic_reviews_assessment_id'))

    op.drop_table('periodic_reviews')
    # 移除本遷移建立的具名型別，否則降級後重新升級會撞名。
    # risklevel 由前一個遷移建立，此處不得移除。
    if bind.dialect.name == "postgresql":
        sa.Enum(name="reviewoutcome").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
